language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: tA2m4QCABg97dGWA6OJPI4sATqzR07juKlUwPc/pRx4XEC79UhL0dANoWpFiy2dUBdRGwogGbDlliYF3q/lJZ+k9JneqLTwVIh26q2Zfbbb3n7LOifxakRGfq5SidZ/5bx7QEXc8Cz7jktV4A/37N9sod4TEkb3sBDjGJCkkJmCbL0ykcO/4Fn7ma8OdvXg5HPzpygaH6D3zrnPiEX6mXHT8cIk/6VXqSQWXZdfh81594fE56d+pAsAu8aaFd1L7VvStBVhWZ0Q8Sk7SECDyuAamBYSrcp+ejJVdKAxtkyt9z1IYyLtTwVKf/YEaZhfu/d4pwlSVlxrzOp4Byotjs9wE2E9MncC4IoLan/AsA/ZsNhhrIw+7cqKtfaqT85otNMJzDgfB92EpJNuaCkkGsA9qZs2PJxJfMIr0VapUAYqIRi0j8fVLX19SoThOOxCtZWBPe9IGgUtXoShMRjj/dtvm5c6HAGbXVvzQjoORbldHauIVH2G4wviUhHSyLbq0TyzpbFMVd0qHLMHag42HL2g/565zOTsh/+gtztnFGgDQzmySuKt0LfR79tLSsHnK0Cp5mmwdJaoiuEWxkpgXyrmnos7Vsq1BVJc0bdRnJ9dPKpLZf5QqBbcyZMYWr47VUdiXdZ99X0OVoJM959zOVFGWI9DcBthTqe4JIOnmrxg=
  app: pacific-bastion-25937
  on:
    repo: Ryca77/alike
